name = "prono-cdm-api"
main = "worker/src/index.ts"
compatibility_date = "2026-06-01"

[observability]
enabled = true

[vars]
FOOTBALL_DATA_COMPETITION = "WC"
FOOTBALL_DATA_SEASON = "2026"
COOKIE_SAMESITE = "None"
COOKIE_SECURE = "true"

[[d1_databases]]
binding = "DB"
database_name = "prono-cdm"
database_id = "3cc561c2-9f9c-4857-9a79-93f882e081ff"
migrations_dir = "migrations"

[triggers]
crons = ["*/30 * * * *"]
